[package]
name = "holo"
version = "0.1.0"
edition = "2021"
authors = ["Manish Kumawat"]

[dependencies]
arrayvec = "0.7.6"

[profile.release]
codegen-units = 1
lto = "fat"
opt-level = 3
panic = "abort"
