[package]
name = "holo"
version = "0.1.0"
edition = "2021"
authors = ["Manish Kumawat"]

[dependencies]
env_logger = "0.11.8"
log = "0.4.27"

[profile.release]
codegen-units = 1
lto = "fat"
opt-level = 3
panic = "abort"
